# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"-\n\x0e\x45nqueueRequest\x12\r\n\x05queue\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\t\n\x07Nothing\"\x18\n\x07QueueID\x12\r\n\x05queue\x18\x01 \x01(\t\"\x1c\n\x0bQueueLength\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\"\x1f\n\x0f\x44\x65queueResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xc6\x01\n\x0cQueueService\x12&\n\x07\x45nqueue\x12\x0f.EnqueueRequest\x1a\x08.Nothing\"\x00\x12\'\n\x07\x44\x65queue\x12\x08.QueueID\x1a\x10.DequeueResponse\"\x00\x12!\n\x05Purge\x12\x08.QueueID\x1a\x0c.QueueLength\"\x00\x12\"\n\x06Length\x12\x08.QueueID\x1a\x0c.QueueLength\"\x00\x12\x1e\n\x06Health\x12\x08.Nothing\x1a\x08.Nothing\"\x00\x42\x07Z\x05./genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\005./gen'
  _globals['_ENQUEUEREQUEST']._serialized_start=17
  _globals['_ENQUEUEREQUEST']._serialized_end=62
  _globals['_NOTHING']._serialized_start=64
  _globals['_NOTHING']._serialized_end=73
  _globals['_QUEUEID']._serialized_start=75
  _globals['_QUEUEID']._serialized_end=99
  _globals['_QUEUELENGTH']._serialized_start=101
  _globals['_QUEUELENGTH']._serialized_end=129
  _globals['_DEQUEUERESPONSE']._serialized_start=131
  _globals['_DEQUEUERESPONSE']._serialized_end=162
  _globals['_QUEUESERVICE']._serialized_start=165
  _globals['_QUEUESERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
